### ISSUE TITLE
Holpersteine beim Seiten-Testlauf...

### ISSUE THREAD

**Issue by Maffotter** [darthkali/DWP-GWP-Project#153]
- [x] Startseite: Klick auf die unteren Bilder öffnet Bild in neuem Tab aber lässt sich nur durch Tabwechsel oder -schließen zurückkehren... Versucht ein typisches "X" oder "Zurück" auf der neuen Seite.

- [x] Bilder im extra Tab mit vergrößerungsfunktion ausstatten.

- [x] Footer: Hover Effekt auch für Social-Links einführen.

- [x] Startseite: Seitenwechsel von "Zur Eventseite" sollte auf entsprechendes Event verankert sein.

- [x] Ausrufezeichen sind keine Rudeltiere.

- [x] Filter in per URL übergeben, damit Einstellungen per Link verschickt werden können

- [x] Events: Event nicht klickbar... Detailseite für jedes Event? 

- [x] Über Uns: Pfeilgrafik vom Kontaktformular mit in den Link packen, damit er ebenfalls klickbar ist.

- [x] Fehler bei der Registrierung werden an verschiedenen Stellen angezeigt. Mal Inline, mal über dem Formular. -> Sonderzeichen und Zahlen- Hinweis sind Inline... Lösung: Alle Passwortspezifischen Fehler Inline darstellen?

**Comment by darthkali** [comment]
Icon oben in der Taskleitse für Darkmode und White Mode

**Comment by darthkali** [comment]
Alles als eigenstehende Issues aufgenommen!
