### ISSUE TITLE
Fehler wenn es keine Events gibt!

### ISSUE THREAD

**Issue by darthkali** [darthkali/DWP-GWP-Project#159]
Wenn ich alle Events lösche, wird der Fehler angezeigt. Dabei geht es um die Berechnung des Datums.

![image](https://user-images.githubusercontent.com/46423967/75099139-92026880-55be-11ea-9395-23c8828d11a3.png)

![image](https://user-images.githubusercontent.com/46423967/75099153-b2cabe00-55be-11ea-8ae9-57fbd9e0616c.png)

**Comment by TotalFlash** [comment]
Habe die Funktionen überarbeitet und etwas anschaulicher gestaltet. Bei mir funktioniert alles. Wäre aber trotzdem cool, wenn du nochmal testen würdest!
